//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedSeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookedSeat()
        {
            this.CancellationReqs = new HashSet<CancellationReq>();
            this.CancelledTickets = new HashSet<CancelledTicket>();
        }
    
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public int seat_id { get; set; }
        public int coach_id { get; set; }
        public int train_id { get; set; }
        public int total_amount { get; set; }
        public int payment_id { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancellationReq> CancellationReqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledTicket> CancelledTickets { get; set; }
    }
}
