//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancellationReq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CancellationReq()
        {
            this.CancelledTickets = new HashSet<CancelledTicket>();
        }
    
        public int cancellationReq_id { get; set; }
        public int booking_id { get; set; }
        public string status { get; set; }
    
        public virtual BookedSeat BookedSeat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledTicket> CancelledTickets { get; set; }
    }
}
