//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int seat_id { get; set; }
        public int coach_id { get; set; }
        public string availability { get; set; }
        public string seat_number { get; set; }
    
        public virtual Coach Coach { get; set; }
    }
}
